/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AreaGrid: typeof import('./src/components/AreaGrid.vue')['default']
    DashboardComponent: typeof import('./src/components/DashboardComponent.vue')['default']
    FactoryFloorMap: typeof import('./src/components/FactoryFloorMap.vue')['default']
    FilterDropdown: typeof import('./src/components/FilterDropdown.vue')['default']
    MachineCard: typeof import('./src/components/MachineCard.vue')['default']
    MachineDetails: typeof import('./src/components/MachineDetails.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateReasonDialog: typeof import('./src/components/UpdateReasonDialog.vue')['default']
  }
}
